linked_list : linked_list.o ../../CI/objects/linked_list/linkedM.o
	gcc --std=c18 linked_list.o ../../CI/objects/linked_list/linkedM.o -o linked_list


linked_list.o : linked_list.c
	gcc --std=c18 -c linked_list.c

